### ISSUE TITLE
An exception is indicated when testing the Bot

### ISSUE THREAD

**Issue by sunyuboalisa** [microsoftgraph/microsoft-graph-comms-samples#101]
**Describe the issue**
i published the AudioVideoPlaybackBot and invited the bot join my meeting. 
it received a 500 Internal Server Error.The details are as follows:
post: https://huebot.cloudapp.net/joinCall
{
    " JoinURL ": "https://teams.microsoft.com/l/meetup-join/19%3a2d05e8c5daf34a88b821f43fee5caba3%40thread.skype/1562307724828?context=%7b%22Tid%22%3a%22d1fc15b9-204e-4b78-9faf-dac73e1b54fb%22%2c%22Oid%22%3a%22e4f3f00e-54e6-43ae-b5ef-6df7e03657d6%22%7d"
}

the response:
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.Text.RegularExpressions.Regex.Match(String input)
   at Sample.Common.Meetings.JoinInfo.ParseJoinURL(String joinURL) in C:\Demo\Samples\Common\Sample.Common\Meetings\JoinInfo.cs:line 34
   at Sample.AudioVideoPlaybackBot.FrontEnd.Bot.Bot.<JoinCallAsync>d__22.MoveNext() in C:\Demo\Samples\V1.0Samples\LocalMediaSamples\AudioVideoPlaybackBot\FrontEnd\Bot\Bot.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.AudioVideoPlaybackBot.FrontEnd.Http.JoinCallController.<JoinCallAsync>d__0.MoveNext() in C:\Demo\Samples\V1.0Samples\LocalMediaSamples\AudioVideoPlaybackBot\FrontEnd\Http\Controllers\JoinCallController.cs:line 46

**Comment by ksikorsk** [comment]
Looks like you have white space around " JoinURL ".

Should be:
```http
post: https://huebot.cloudapp.net/joinCall
{
  "JoinURL": "https://teams.microsoft.com/l/meetup-join/19%3a2d05e8c5daf34a88b821f43fee5caba3%40thread.skype/1562307724828?context=%7b%22Tid%22%3a%22d1fc15b9-204e-4b78-9faf-dac73e1b54fb%22%2c%22Oid%22%3a%22e4f3f00e-54e6-43ae-b5ef-6df7e03657d6%22%7d"
}
```
