### ISSUE TITLE
Service Exception when trying to add participant to create a multiparty / group call

### ISSUE THREAD

**Issue by tinsheep** [microsoftgraph/microsoft-graph-comms-samples#119]
Hi - I'm trying to get two parties together in a call. Works fine with the straight IncidentBot sample when I add them to a pre-existing meeting that I have created. However, I would like to just have that meeting created ad hoc and connect to the two parties. I saw issue 64 which showed that the Client.Calls().AddAsync won't work yet when I add two targets (tried that first). Then I saw the note to make a call to user1 and then add a participant user2. I did this with Client.Calls( [callLegId].Participants.InviteAsync - passing in the statefulCall.Id of the user1 call.  Note that my ReplacesCallId is null because there is no call to replace I'm just adding a participant is that OK? Is that the way I should be creating a multiparty call for now? When I call the InviteAsync I'm getting:

	Status Code: 0
	Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 500
	Message: Unexpected 'Failed' status for operation 033a359b-81bf-400f-9de0-7869c4124519:
	Object reference not set to an instance of an object.
	
	   at Microsoft.Graph.Communications.Client.OperationManager.ValidateOperation(String clientContext, CommsOperation operation)
	   at Microsoft.Graph.Communications.Client.OperationManager.<WaitForCompletionAsync>d__10`1.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.Graph.Communications.Calls.StatefulParticipantCollection.<InviteAsync>d__2.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
	   at Sample.IncidentBot.Bot.Bot.<AddParticipantAsync>d__32.MoveNext() in C:\dev\git\microsoft-graph-comms-samples\Samples\BetaSamples\RemoteMediaSamples\IncidentBot\Bot\Bot.cs…….. 

Thanks for any help.

**Comment by ksikorsk** [comment]
> Client.Calls()[callLegId].Participants.InviteAsync - passing in the statefulCall.Id of the user1 call.

You should be passing in the the identity of the participant you are trying to invite, not the call id.
