### ISSUE TITLE
Call Not Found Exception : Microsoft.Graph.Communications

### ISSUE THREAD

**Issue by aarushi-mittal** [microsoftgraph/microsoft-graph-comms-samples#173]
Hello ,
@ksikorsk

I am following the audio video bot tutorial.
I have tried the joinCall.

I do receive a legID.

However I do not know the url to make the bot join the call.
I assume that's the reason why I get an Exception as follows :

> Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 8522

> Message: Call not found.

- Aarushi

**Comment by ksikorsk** [comment]
@zhengni-msft @ananmishr @paywuAtMicrosoft

**Comment by aarushi-mittal** [comment]
Hello Team,

I have followed all steps as suggested in the tutorial.
But I still get this error.

I have used a custom dns generated  using Azure App service domain names and certificates.

Kindly help me out with this.

Let me know any logs or information you would require.

Regards
Aarushi

**Comment by paywuAtMicrosoft** [comment]
Hi Aarushi,
Can you provide a call-id and the time you made the call?

**Comment by aarushi-mittal** [comment]
Hello,

I am able to resolve this issue.

Kindly suggest if this bot has access to real-time audio streams.
I want to read the audio streams of the users on the call via the bot

-Aarushi

**Comment by paywuAtMicrosoft** [comment]
Hi Aarushi,

If you go to BotMediaStream.cs, there is a 
this.audioSocket.AudioSendStatusChanged += this.OnAudioSendStatusChanged;

You can follow the example and add a a event handler for 
this.audioSocket.AudioMediaReceived 


The AudioMediaReceived event is raised each time a packet of audio media is received.

**Comment by aarushi-mittal** [comment]
Hello @paywuAtMicrosoft ,
Thank you for being so spontaneous with the response.
I am trying to save/read the audio streams.

I found the fileStream in Utilities.cs where Audio is written, however I am not aware how I can read that. Kindly suggest if I can read data in Utilities.cs

Also suggest where I can read GraphLogger logs. I am new to C# so I am still in the learning phase.

Regards,
Aarushi

**Comment by bijaykush** [comment]
@aarushi-mittal 
If that is the exact place in AudioVideo Bot to receive audio streams, you can save those incoming audio streams into a file (disk) with the help of C# and then you can use FFMEPG converter to convert that raw data file into the required audio format.
I hope this will help you.

**Comment by aarushi-mittal** [comment]
Hello @bijaykush ,

I am using this:

However , the size of file is very small.
`private void OnAudioMediaReceived(object sender, AudioMediaReceivedEventArgs e)
        {
            this.logger.Info($"Received Audio: [VideoMediaReceivedEventArgs(Data=<{e.Buffer.Data.ToString()}>, Length={e.Buffer.Length}, Timestamp={e.Buffer.Timestamp})]");
System.IO.File.AppendAllText("data2.txt", Marshal.ReadInt32(e.Buffer.Data).ToString());
            System.IO.File.AppendAllText("data2.txt", " ");
            System.IO.File.AppendAllText("silence.txt", e.Buffer.IsSilence.ToString());
e.Buffer.Dispose();
        }`

however, the size is only 225KB for a span of 5-10 minutes . 

Plus the audio has only noise in it

Regards,
Aarushi

**Comment by roygarbriceno** [comment]
> Hello,
> 
> I am able to resolve this issue.
> 
> Kindly suggest if this bot has access to real-time audio streams.
> I want to read the audio streams of the users on the call via the bot
> 
> -Aarushi

HI, How are you?, I'm, getting the same "call not found error" error, you said where able to solve it, can you please explain what was solution in your case?, thanks

**Comment by carynbear** [comment]
I am also having this error @paywuAtMicrosoft @aarushi-mittal

**Comment by MurtazaMultanWala** [comment]
hey @aarushi-mittal, I am also facing the similar problem i.e. 

> Exception thrown: 'Microsoft.Graph.Communications.Core.Exceptions.ServiceException' in mscorlib.dll

can you please brief the problem causing this error and steps taken to resolve it.

**Comment by harishvadali** [comment]
I am seeing this same error "call not found". The `joincall` returned with `200 OK`. But the bot did not join and I see this `call not found` error in the logs.
```
[HeartbeatHandler.cs:74 HeartbeatDetected] Caught an Exception running the task: RecordingBot.Services.Bot.CallHandler.HeartbeatAsync(args)
exception: Code: 8522
Message: Call not found.
Scenario Id: 712aa2cb-204d-4e4c-a86e-99ccf4c26d14
Inner error:
	AdditionalData:
	date: 2021-05-06T05:26:40
	request-id: 7ebde706-ab9e-4495-b901-7ab4b0ce91ba
	client-request-id: 28b200d4-5ea9-4b3d-8cc7-ba3145d404e9

Code: 8522
Message: Call not found.
Inner error:
	AdditionalData:
	date: 2021-05-06T05:26:40
	request-id: 7ebde706-ab9e-4495-b901-7ab4b0ce91ba
	client-request-id: 28b200d4-5ea9-4b3d-8cc7-ba3145d404e9

StackTrace:    at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Common.Transport.GraphHttpClient.<SendAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
```
```
[GraphAuthClient.cs:117 SendHttpRequestAsync] {
  "error": {
    "code": "8522",
    "message": "Call not found.",
    "innererror": {
      "date": "2021-05-06T05:17:30",
      "request-id": "6b8ddac4-7a1c-4f95-bc38-5f778e3f1884",
      "client-request-id": "8d42a911-de98-461a-877b-aa3a8e0403eb"
    }
  }
}
```

**Comment by babunirwan** [comment]
Same issue while using the Answer graph API.
"error": {
        "code": "8522",
        "message": "Call not found.",
        "innerError": {
            "date": "2022-05-31T05:41:12",
            "request-id": "b31e505e-c39b-47c8-98db-7fd310756614",
            "client-request-id": "b31e505e-c39b-47c8-98db-7fd310756614"
        }
    }
}

Any update on the issue??

**Comment by MaslinuPoimal** [comment]
We are also having this issue on all new deployments. Is it known what causes it?

**Comment by babunirwan** [comment]
Hi,

Just if anyone above has idea about the same -

We need to make PSTN direct extension calls to agents using MS teams only. But don't know how to involve bot in the same to get the events. We are trying to integrate in our CRM using graph API.

Any suggestion please .
