### ISSUE TITLE
Having trouble getting Incident Bot to work. Unexpected id format, Get is not supported via graph v1.0

### ISSUE THREAD

**Issue by shortboard** [microsoftgraph/microsoft-graph-comms-samples#183]
I am trying to get the sample of Incident Bot to run but i'm receiving an bad request error "Microsoft.Graph.ServiceException: Code: BadRequest Message: Unexpected id format, Get is not supported via graph v1.0". When i first downloaded it the solution had `Sample.Common.Beta` included but IncidentBot referenced `Sample.Common`, when i first got this error i tried referencing `Sample.Common.Beta` instead but the error remains. I'm wondering if there is something wrong with my postman call or do i need to make some changes to the project?

**Postman Call**
```javascript
{
  "name": "New Incident", 
  "time": "2020-03-03T04:06:08+00:00", 
  "tenantId": "f102fd0a-0470-48c9-b606-4a522309971c",
  "objectIds": [
      "fb73281b-037d-48bb-80b6-2c1b00c6f28c",
      "be074941-5d68-4f9b-af7d-30c6f2481086"
  ],
  "meetingId": "fb73281b-037d-48bb-80b6-2c1b00c6f28c_19:meeting_YTM3YTkzZDgtYzM2YS00ZmQ0LTk2ZWMtZjNkZDhiYWIwMDFj%40thread.v2",
  "joinURL": "https://teams.microsoft.com/l/meetup-join/19%3ameeting_YTM3YTkzZDgtYzM2YS00ZmQ0LTk2ZWMtZjNkZDhiYWIwMDFj%40thread.v2/0?context=%7b%22Tid%22%3a%22f102fd0a-0470-48c9-b606-4a522309971c%22%2c%22Oid%22%3a%22fb73281b-037d-48bb-80b6-2c1b00c6f28c%22%7d",
  "removeFromDefaultRoutingGroup": true,
  "allowConversationWithoutHost": true
}
```

**Full Error Response**
```
Status Code: BadRequest
Microsoft.Graph.ServiceException: Code: BadRequest
Message: Unexpected id format, Get is not supported via graph v1.0
Inner error:
	AdditionalData:
	request-id: 930c2c4e-5aea-4aac-8e13-df748191f5a4
	date: 2020-03-03T05:15:56
ClientRequestId: e219eb9f-9dc7-47fa-afa4-071df594e932

   at Microsoft.Graph.HttpProvider.<SendAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendRequestAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.BaseRequest.<SendAsync>d__31`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.OnlineMeetingRequest.<GetAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.Common.OnlineMeetings.OnlineMeetingHelper.<GetOnlineMeetingAsync>d__3.MoveNext() in C:\Users\DamienSimpson\Desktop\c\c\Samples\Common\Sample.Common\OnlineMeetingsHelper\OnlineMeetingHelper.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.IncidentBot.Bot.Bot.<JoinCallAsync>d__28.MoveNext() in C:\Users\DamienSimpson\Desktop\c\c\Samples\V1.0Samples\RemoteMediaSamples\IncidentBot\Bot\Bot.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.IncidentBot.Bot.Bot.<RaiseIncidentAsync>d__27.MoveNext() in C:\Users\DamienSimpson\Desktop\c\c\Samples\V1.0Samples\RemoteMediaSamples\IncidentBot\Bot\Bot.cs:line 213
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IcMBot.Controllers.IncidentsController.<PostIncidentAsync>d__3.MoveNext() in C:\Users\DamienSimpson\Desktop\c\c\Samples\V1.0Samples\RemoteMediaSamples\IncidentBot\Controllers\IncidentsController.cs:line 52
```

**Graph SDK:**
Beta 0.10.0-preview

**Call ID**
930c2c4e-5aea-4aac-8e13-df748191f5a4 2020-03-03T05:15:56

**Comment by ksikorsk** [comment]
You need to specify `joinUrl` OR `meetingId`.  In your case it's the `joinUri`.  `meetingId` is something completely different, and should probably be removed from this sample as it creates confusion.

@paywuAtMicrosoft @yizhenww

**Comment by zihzhan** [comment]
The {meetingId} here refer to the VTC Conference ID.
![TestMeeting1 png](https://user-images.githubusercontent.com/43592314/80417830-448acc00-888b-11ea-8f0a-57e0c7bb8b30.png)

It’s alternative. If the meeting created is a VTC meeting and **{videoTeleconferenceId}** is provided in request body, then **{videoTeleconferenceId}** will be used as a replacement of **{joinURL}**.

I raised a PR change this property's name {meetingId} to {videoTeleconferenceId}
