### ISSUE TITLE
Error on anwering call the first time the bot application starts.

### ISSUE THREAD

**Issue by jsweiler** [microsoftgraph/microsoft-graph-comms-samples#191]
**Describe the issue**
I have taken the remote media sample application and published it to an Azure App Service. The issue I have is on the first call to my resource account from a Teams client the call fails in Teams and I get a few errors from the logs which I have below.

**Expected behavior**
I would expect the `Call.Answer()` to succeed.

**Graph SDK (please complete the following information):**
 - Version 1.2.0-beta.1

**Call ID**
521f0b00-431f-49e4-972a-d4da044def36, 2020-03-11T18:41:32.7101527Z

**Logs**
``` txt
$>2020-03-11T18:41:34.3167890Z Error: Bot.cs:450 CallsOnIncoming
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
Exception happened when answering the call.
exception: Code: 8522
Message: Call not found.
Scenario Id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
Inner error:
	AdditionalData:
	request-id: ab00e78c-1d63-40a0-b165-5c909eb3d685
	date: 2020-03-11T18:41:34

Code: 8522
Message: Call not found.
Inner error:
	AdditionalData:
	request-id: ab00e78c-1d63-40a0-b165-5c909eb3d685
	date: 2020-03-11T18:41:34

StackTrace:    at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
$>2020-03-11T18:41:34.3167890Z Error: GraphAuthClient.cs:117 SendHttpRequestAsync
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
CallId: 521f0b00-431f-49e4-972a-d4da044def36
TenantId: 1cd119ab-b444-4c16-84b9-8538585d1987
TransactionDirection: Outgoing
TraceType: HttpResponse
ResponseTime: 454
request: POST https://graph.microsoft.com/beta/communications/calls/521f0b00-431f-49e4-972a-d4da044def36/microsoft.graph.answer
response: 404 NotFound
headers:
  request-id: ab00e78c-1d63-40a0-b165-5c909eb3d685
  client-request-id: 8611e5b2-0483-4782-82d9-5dec18c0a4ef
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_14"}}
  scenario-id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
  Strict-Transport-Security: max-age=31536000
  Cache-Control: private
  Date: Wed, 11 Mar 2020 18:41:33 GMT
  Content-Length: 205
  Content-Type: application/json
{
  "error": {
    "code": "8522",
    "message": "Call not found.",
    "innererror": {
      "request-id": "ab00e78c-1d63-40a0-b165-5c909eb3d685",
      "date": "2020-03-11T18:41:34"
    }
  }
}
$>2020-03-11T18:41:34.2394667Z Error: Bot.cs:450 CallsOnIncoming
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
Exception happened when answering the call.
exception: Code: 8522
Message: Call not found.
Scenario Id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
Inner error:
	AdditionalData:
	request-id: 2244abc0-bca4-4423-a2bf-5d15b2c5db09
	date: 2020-03-11T18:41:34

Code: 8522
Message: Call not found.
Inner error:
	AdditionalData:
	request-id: 2244abc0-bca4-4423-a2bf-5d15b2c5db09
	date: 2020-03-11T18:41:34

StackTrace:    at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
$>2020-03-11T18:41:34.1917543Z Error: GraphAuthClient.cs:117 SendHttpRequestAsync
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
CallId: 521f0b00-431f-49e4-972a-d4da044def36
TenantId: 1cd119ab-b444-4c16-84b9-8538585d1987
TransactionDirection: Outgoing
TraceType: HttpResponse
ResponseTime: 267
request: POST https://graph.microsoft.com/beta/communications/calls/521f0b00-431f-49e4-972a-d4da044def36/microsoft.graph.answer
response: 404 NotFound
headers:
  request-id: 2244abc0-bca4-4423-a2bf-5d15b2c5db09
  client-request-id: f0d2c788-bf26-4578-8350-069a2721fc73
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"002","RoleInstance":"AGSFE_IN_62"}}
  scenario-id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
  Strict-Transport-Security: max-age=31536000
  Cache-Control: private
  Date: Wed, 11 Mar 2020 18:41:33 GMT
  Content-Length: 205
  Content-Type: application/json
{
  "error": {
    "code": "8522",
    "message": "Call not found.",
    "innererror": {
      "request-id": "2244abc0-bca4-4423-a2bf-5d15b2c5db09",
      "date": "2020-03-11T18:41:34"
    }
  }
}
$>2020-03-11T18:41:33.8963323Z Info: GraphAuthClient.cs:100 SendHttpRequestAsync
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
CallId: 521f0b00-431f-49e4-972a-d4da044def36
TenantId: 1cd119ab-b444-4c16-84b9-8538585d1987
TransactionDirection: Outgoing
TraceType: HttpRequest
request: POST https://graph.microsoft.com/beta/communications/calls/521f0b00-431f-49e4-972a-d4da044def36/microsoft.graph.answer
headers:
  Scenario-Id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
  Client-Request-Id: f0d2c788-bf26-4578-8350-069a2721fc73
  User-Agent: GraphCommunicationsClient-IncidentBot/1.2.0.1
  Authorization: (redacted)
  Content-Type: application/json; charset=utf-8
{
  "callbackUri": "https://incidentbotcommssamples.azurewebsites.net/callback/calling?webInstanceId=a96167f52c61bd304d7412a6e5d00edca25241f6cc950684909c9162b784055b",
  "mediaConfig": {
    "@odata.type": "#microsoft.graph.serviceHostedMediaConfig",
    "preFetchMedia": [
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/responder-transfering.wav",
        "resourceId": "bb593339-3cd8-4c41-b047-b40aecd2bac8"
      },
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/responder-notification.wav",
        "resourceId": "140573b7-ed43-4c81-a89f-fc7dfc33d83a"
      },
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/bot-incoming.wav",
        "resourceId": "67b1033b-08a3-45e6-b6b2-9990a8a573d1"
      },
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/bot-endpoint-incoming.wav",
        "resourceId": "d6f84655-c185-41d4-a32a-acce50fd5136"
      }
    ]
  },
  "acceptedModalities": [
    "audio"
  ]
}
$>2020-03-11T18:41:33.8669294Z Info: GraphAuthClient.cs:100 SendHttpRequestAsync
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
CallId: 521f0b00-431f-49e4-972a-d4da044def36
TenantId: 1cd119ab-b444-4c16-84b9-8538585d1987
TransactionDirection: Outgoing
TraceType: HttpRequest
request: POST https://graph.microsoft.com/beta/communications/calls/521f0b00-431f-49e4-972a-d4da044def36/microsoft.graph.answer
headers:
  Scenario-Id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
  Client-Request-Id: 8611e5b2-0483-4782-82d9-5dec18c0a4ef
  User-Agent: GraphCommunicationsClient-IncidentBot/1.2.0.1
  Authorization: (redacted)
  Content-Type: application/json; charset=utf-8
{
  "callbackUri": "https://incidentbotcommssamples.azurewebsites.net/callback/calling?webInstanceId=a96167f52c61bd304d7412a6e5d00edca25241f6cc950684909c9162b784055b",
  "mediaConfig": {
    "@odata.type": "#microsoft.graph.serviceHostedMediaConfig",
    "preFetchMedia": [
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/responder-transfering.wav",
        "resourceId": "bb593339-3cd8-4c41-b047-b40aecd2bac8"
      },
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/responder-notification.wav",
        "resourceId": "140573b7-ed43-4c81-a89f-fc7dfc33d83a"
      },
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/bot-incoming.wav",
        "resourceId": "67b1033b-08a3-45e6-b6b2-9990a8a573d1"
      },
      {
        "@odata.type": "#microsoft.graph.mediaInfo",
        "uri": "https://incidentbotcommssamples.azurewebsites.net/audio/bot-endpoint-incoming.wav",
        "resourceId": "d6f84655-c185-41d4-a32a-acce50fd5136"
      }
    ]
  },
  "acceptedModalities": [
    "audio"
  ]
}
$>2020-03-11T18:41:33.3315265Z Info: CommunicationsClientExtensions.cs:153 LogAndCreateResponse
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 13959
request: POST https://incidentbotcommssamples.azurewebsites.net/callback/calling
response: 202 Accepted
headers:
  Client-Request-Id: a1e9f1de-60cc-44aa-ac41-19fb32a0d580
  Scenario-Id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
$>2020-03-11T18:41:33.3315265Z Info: CommunicationsClientExtensions.cs:151 LogAndCreateResponse
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST https://incidentbotcommssamples.azurewebsites.net/callback/calling
headers:
  Connection: Keep-Alive
  Accept: application/json
  Authorization: (redacted)
  Host: incidentbotcommssamples.azurewebsites.net
  Max-Forwards: (redacted)
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  X-Microsoft-Skype-Chain-ID: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
  X-Microsoft-Skype-Caller-Region: amer
  X-Microsoft-Skype-Callee-Region: amer
  X-Microsoft-Skype-Message-ID: a1e9f1de-60cc-44aa-ac41-19fb32a0d580
  X-Microsoft-Skype-Original-Message-ID: 00e3f297-3e13-4766-af16-04be8fd89bd2
  X-WAWS-Unencoded-URL: (redacted)
  CLIENT-IP: (redacted)
  X-ARR-LOG-ID: (redacted)
  DISGUISED-HOST: (redacted)
  X-SITE-DEPLOYMENT-ID: (redacted)
  WAS-DEFAULT-HOSTNAME: (redacted)
  X-Original-URL: (redacted)
  X-Forwarded-For: (redacted)
  X-ARR-SSL: (redacted)
  X-Forwarded-Proto: (redacted)
  X-AppService-Proto: (redacted)
  MS-ASPNETCORE-TOKEN: (redacted)
  X-Original-For: (redacted)
  X-Original-Proto: (redacted)
  Content-Type: application/json
  Content-Length: 1602
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "created",
      "resourceUrl": "/communications/calls/521f0b00-431f-49e4-972a-d4da044def36",
      "resource": "/app/calls/521f0b00-431f-49e4-972a-d4da044def36",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "incoming",
        "direction": "incoming",
        "callbackUri": "https://incidentbotcommssamples.azurewebsites.net/callback/calling",
        "source": {
          "@odata.type": "#microsoft.graph.participantInfo",
          "identity": {
            "@odata.type": "#microsoft.graph.identitySet",
            "user": {
              "@odata.type": "#microsoft.graph.identity",
              "id": "73146471-c389-40cc-b690-227d58584b93",
              "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987"
            }
          },
          "endpointType": "default",
          "region": "amer",
          "languageId": "en-us",
          "id": "19b2b05c-e2db-40be-83da-36496b2e1387"
        },
        "targets": [
          {
            "@odata.type": "#microsoft.graph.invitationParticipantInfo",
            "identity": {
              "@odata.type": "#microsoft.graph.identitySet",
              "applicationInstance": {
                "@odata.type": "#microsoft.graph.identity",
                "id": "92167092-d0e9-4fe7-b51a-fea8c3b0e0ce",
                "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987"
              }
            },
            "endpointType": "default",
            "id": "1a3b251c-7311-4a70-bb52-5b6b83346f24",
            "region": "amer",
            "languageId": null
          }
        ],
        "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987",
        "myParticipantId": "1a3b251c-7311-4a70-bb52-5b6b83346f24",
        "incomingContext": {
          "@odata.type": "#microsoft.graph.incomingContext",
          "sourceParticipantId": "19b2b05c-e2db-40be-83da-36496b2e1387"
        },
        "id": "521f0b00-431f-49e4-972a-d4da044def36",
        "callChainId": "9c0c1f04-9102-4f0e-a8fc-59532912e3f4"
      }
    }
  ]
}
$>2020-03-11T18:41:32.9747586Z Info: CommunicationsClientExtensions.cs:153 LogAndCreateResponse
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 7778
request: POST https://incidentbotcommssamples.azurewebsites.net/callback/calling
response: 202 Accepted
headers:
  Client-Request-Id: 63ab2182-9386-4dbc-ab47-46feca51b3ac
  Scenario-Id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
$>2020-03-11T18:41:32.9455622Z Info: CommunicationsClientExtensions.cs:153 LogAndCreateResponse
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
TransactionDirection: Incoming
TraceType: HttpResponse
ResponseTime: 2882
request: POST https://incidentbotcommssamples.azurewebsites.net/callback/calling
response: 202 Accepted
headers:
  Client-Request-Id: 74b457f3-da24-4377-8c8d-6efc0e3a8d18
  Scenario-Id: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
$>2020-03-11T18:41:32.7392295Z Info: CommunicationsClientExtensions.cs:151 LogAndCreateResponse
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST https://incidentbotcommssamples.azurewebsites.net/callback/calling
headers:
  Connection: Keep-Alive
  Accept: application/json
  Authorization: (redacted)
  Host: incidentbotcommssamples.azurewebsites.net
  Max-Forwards: (redacted)
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  X-Microsoft-Skype-Chain-ID: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
  X-Microsoft-Skype-Caller-Region: amer
  X-Microsoft-Skype-Callee-Region: amer
  X-Microsoft-Skype-Message-ID: 63ab2182-9386-4dbc-ab47-46feca51b3ac
  X-Microsoft-Skype-Original-Message-ID: 00e3f297-3e13-4766-af16-04be8fd89bd2
  X-WAWS-Unencoded-URL: (redacted)
  CLIENT-IP: (redacted)
  X-ARR-LOG-ID: (redacted)
  DISGUISED-HOST: (redacted)
  X-SITE-DEPLOYMENT-ID: (redacted)
  WAS-DEFAULT-HOSTNAME: (redacted)
  X-Original-URL: (redacted)
  X-Forwarded-For: (redacted)
  X-ARR-SSL: (redacted)
  X-Forwarded-Proto: (redacted)
  X-AppService-Proto: (redacted)
  MS-ASPNETCORE-TOKEN: (redacted)
  X-Original-For: (redacted)
  X-Original-Proto: (redacted)
  Content-Type: application/json
  Content-Length: 1602
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "created",
      "resourceUrl": "/communications/calls/521f0b00-431f-49e4-972a-d4da044def36",
      "resource": "/app/calls/521f0b00-431f-49e4-972a-d4da044def36",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "incoming",
        "direction": "incoming",
        "callbackUri": "https://incidentbotcommssamples.azurewebsites.net/callback/calling",
        "source": {
          "@odata.type": "#microsoft.graph.participantInfo",
          "identity": {
            "@odata.type": "#microsoft.graph.identitySet",
            "user": {
              "@odata.type": "#microsoft.graph.identity",
              "id": "73146471-c389-40cc-b690-227d58584b93",
              "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987"
            }
          },
          "endpointType": "default",
          "region": "amer",
          "languageId": "en-us",
          "id": "19b2b05c-e2db-40be-83da-36496b2e1387"
        },
        "targets": [
          {
            "@odata.type": "#microsoft.graph.invitationParticipantInfo",
            "identity": {
              "@odata.type": "#microsoft.graph.identitySet",
              "applicationInstance": {
                "@odata.type": "#microsoft.graph.identity",
                "id": "92167092-d0e9-4fe7-b51a-fea8c3b0e0ce",
                "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987"
              }
            },
            "endpointType": "default",
            "id": "1a3b251c-7311-4a70-bb52-5b6b83346f24",
            "region": "amer",
            "languageId": null
          }
        ],
        "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987",
        "myParticipantId": "1a3b251c-7311-4a70-bb52-5b6b83346f24",
        "incomingContext": {
          "@odata.type": "#microsoft.graph.incomingContext",
          "sourceParticipantId": "19b2b05c-e2db-40be-83da-36496b2e1387"
        },
        "id": "521f0b00-431f-49e4-972a-d4da044def36",
        "callChainId": "9c0c1f04-9102-4f0e-a8fc-59532912e3f4"
      }
    }
  ]
}
$>2020-03-11T18:41:32.7101527Z Info: CommunicationsClientExtensions.cs:151 LogAndCreateResponse
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
TransactionDirection: Incoming
TraceType: HttpRequest
request: POST https://incidentbotcommssamples.azurewebsites.net/callback/calling
headers:
  Connection: Keep-Alive
  Accept: application/json
  Authorization: (redacted)
  Host: incidentbotcommssamples.azurewebsites.net
  Max-Forwards: (redacted)
  User-Agent: Microsoft-Skype/3.0,(Calling/1.0)
  X-Microsoft-Skype-Chain-ID: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
  X-Microsoft-Skype-Message-ID: 74b457f3-da24-4377-8c8d-6efc0e3a8d18
  X-Microsoft-Skype-Original-Message-ID: c22b661d-ebd6-4d40-b39f-e8a0cae7c280
  X-WAWS-Unencoded-URL: (redacted)
  CLIENT-IP: (redacted)
  X-ARR-LOG-ID: (redacted)
  DISGUISED-HOST: (redacted)
  X-SITE-DEPLOYMENT-ID: (redacted)
  WAS-DEFAULT-HOSTNAME: (redacted)
  X-Original-URL: (redacted)
  X-Forwarded-For: (redacted)
  X-ARR-SSL: (redacted)
  X-Forwarded-Proto: (redacted)
  X-AppService-Proto: (redacted)
  MS-ASPNETCORE-TOKEN: (redacted)
  X-Original-For: (redacted)
  X-Original-Proto: (redacted)
  Content-Type: application/json
  Content-Length: 1781
{
  "@odata.type": "#microsoft.graph.commsNotifications",
  "value": [
    {
      "@odata.type": "#microsoft.graph.commsNotification",
      "changeType": "deleted",
      "resourceUrl": "/communications/calls/521f0b00-431f-49e4-972a-d4da044def36",
      "resource": "/app/calls/521f0b00-431f-49e4-972a-d4da044def36",
      "resourceData": {
        "@odata.type": "#microsoft.graph.call",
        "state": "terminated",
        "resultInfo": {
          "@odata.type": "#microsoft.graph.resultInfo",
          "code": 408,
          "subcode": 8544,
          "message": "Callee could not be reached."
        },
        "terminationReason": "Callee could not be reached.",
        "direction": "incoming",
        "callbackUri": "https://incidentbotcommssamples.azurewebsites.net/callback/calling",
        "source": {
          "@odata.type": "#microsoft.graph.participantInfo",
          "identity": {
            "@odata.type": "#microsoft.graph.identitySet",
            "user": {
              "@odata.type": "#microsoft.graph.identity",
              "id": "73146471-c389-40cc-b690-227d58584b93",
              "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987"
            }
          },
          "endpointType": "default",
          "region": "amer",
          "languageId": "en-us",
          "id": "19b2b05c-e2db-40be-83da-36496b2e1387"
        },
        "targets": [
          {
            "@odata.type": "#microsoft.graph.invitationParticipantInfo",
            "identity": {
              "@odata.type": "#microsoft.graph.identitySet",
              "applicationInstance": {
                "@odata.type": "#microsoft.graph.identity",
                "id": "92167092-d0e9-4fe7-b51a-fea8c3b0e0ce",
                "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987"
              }
            },
            "endpointType": "default",
            "id": "1a3b251c-7311-4a70-bb52-5b6b83346f24",
            "region": "amer",
            "languageId": null
          }
        ],
        "tenantId": "1cd119ab-b444-4c16-84b9-8538585d1987",
        "myParticipantId": "1a3b251c-7311-4a70-bb52-5b6b83346f24",
        "incomingContext": {
          "@odata.type": "#microsoft.graph.incomingContext",
          "sourceParticipantId": "19b2b05c-e2db-40be-83da-36496b2e1387"
        },
        "id": "521f0b00-431f-49e4-972a-d4da044def36",
        "callChainId": "9c0c1f04-9102-4f0e-a8fc-59532912e3f4"
      }
    }
  ]
}
$>2020-03-11T18:41:32.2377906Z Warning: NotificationDispatcher.cs:171 ProcessNotification
ScenarioId: 9c0c1f04-9102-4f0e-a8fc-59532912e3f4
AppId: 8c752766-96bf-494c-8469-77406d4c7a86
AppName: IncidentBot
No queue or registered callbacks for
Deleted: /communications/calls/521f0b00-431f-49e4-972a-d4da044def36
```

**Additional context**
If I call again any number of times it will then work until I restart the web app in Azure. Then it will have the same failure the first time.

**Comment by jsweiler** [comment]
Just a note that it seems if I switch to using v1 (non beta) of the graph sdk that I don't get the issue described above. Were there some things that were fixed in the v1 version?

**Comment by JapNolt** [comment]
@ananmishr @ksikorsk @ssulzer Could any of you please comment on this issue?

**Comment by ssulzer** [comment]
@zhengni-msft @satyakonmsft Can you help look.

**Comment by paywuAtMicrosoft** [comment]
@jsweiler  in the description, you mentioned answering call failed for the first time, so it worked for the second time? The logs you provided are in the reversed order. Can you try beta again and provide the full logs in order?

**Comment by jsweiler** [comment]
I did try it again in. The first time it failed to answer and then the second time it did successfully answer. I copied the logs from the /logs endpoint of the sample remote media application, so the newest is at the top.
[logs.zip](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/4495173/logs.zip)

**Comment by paywuAtMicrosoft** [comment]
@jsweiler, the first log is "deleted. callee could not be reached" this means the bot didn't respond within 5 seconds or didn't answer within 15 seconds. If answer failed for the first time only, please check the network connection.

**Comment by jsweiler** [comment]
Ok, the confusing thing is if I take this app (the sample app from this repo) and use the v1 graph sdk the first call in will work just fine. There are no other code changes just using differenct graph nuget packages. Is there something in the beta graph sdk that would take longer to answer?

**Comment by paywuAtMicrosoft** [comment]
@jsweiler no, there is no extra check for beta graph sdk. Is it 100% repro?

**Comment by jsweiler** [comment]
@paywuAtMicrosoft In my testing is consistently always works the first time with the v1 sdk and consistently doesn't work when I use the beta sdk.

**Comment by zihzhan** [comment]
@jsweiler I was trying to reproduce the issue you describe by using the Incident sample bot with reference to Beta Nuget. Seems like I didn't hit that issue.  Did you use the same sample code as we provided?

**Comment by jsweiler** [comment]
Yes, I simply published the IncidentBot project to an Azure app service.

**Comment by vonguyen1982** [comment]
I got same issue. how did you sort it out ?

**Comment by vonguyen1982** [comment]
Im using v1 and always hit this issue when restart service. Even if A calls B and B decline. A try call again then it will go to voice mail.

**Comment by tares003** [comment]
Any solution to this yet?
