### ISSUE TITLE
MediaApiNotInitialized Exception

### ISSUE THREAD

**Issue by oleksii-gudz** [microsoftgraph/microsoft-graph-comms-samples#192]
Hi Guys,

I have created SF cluster in Azure and uploaded HueBot there. I followed an example with joining the call by post url

{
   "JoinURL": "https://teams.microsoft.com/l/meetup-join/19%3a8c4b1ec81d4444e88ed9955e55a51e91%40thread.tacv2/1584547995167?context=%7b%22Tid%22%3a%224c17d7c9-b866-4ce2-bf4c-987e39a294e8%22%2c%22Oid%22%3a%22ca10881f-81dc-417b-acb7-93cceb274341%22%7d"
}

 but getting exception:

Microsoft.Skype.Bots.Media.SkypeMediaException: Exception of type 'Microsoft.Skype.Bots.Media.SkypeMediaException' was thrown. ---> Microsoft.Rtc.Internal.Media.MediaApi.MediaApiNotInitializedException: Encountered MediaApiNotInitialized Exception
   at Microsoft.Rtc.Internal.Media.MediaApi.MediaPlatform.CreateRenderSession(IDictionary`2 properties, String callId)
   at Microsoft.Skype.Bots.Media.MediaApiPlatformWrapper.CreateRenderSession(IDictionary`2 properties, String callId)
   --- End of inner exception stack trace ---
   at Microsoft.Skype.Bots.Media.MediaApiPlatformWrapper.CreateRenderSession(IDictionary`2 properties, String callId)
   at Microsoft.Skype.Bots.Media.RenderMediaSession..ctor(MediaModality modality, MediaBufferReadyCallBack mediaBufferReadyCallback, String callId, Boolean bypassDecoding, IMediaApiRenderSession mediaApiRenderSession)
   at Microsoft.Skype.Bots.Media.AudioMediaSession.Initialize(StreamDirection enabledStreamDirections, MediaBufferReadyCallBack mediaBufferReadyCallback, AudioFormat supportedAudioFormat, SendStatusChangedCallback sendStatusChangedCallback, String callId, IMediaApiAudioSourceConsumer sourceConsumer)
   at Microsoft.Skype.Bots.Media.AudioMediaSession.Initialize(StreamDirection enabledStreamDirections, MediaBufferReadyCallBack mediaBufferReadyCallback, AudioFormat supportedAudioFormat, SendStatusChangedCallback sendStatusChangedCallback, String callId)
   at Microsoft.Skype.Bots.Media.AudioSocket..ctor(AudioSocketSettings settings, IAudioMediaSession mediaSession, IAudioSocketMetricsCollector metricsCollector, Boolean isTest)
   at Microsoft.Graph.Communications.Calls.Media.MediaSocketFactory.CreateSocket(AudioSocketSettings settings)
   at Microsoft.Graph.Communications.Calls.Media.MediaSession.CreateAudioSocket(Guid mediaSessionId, AudioSocketSettings settings)
   at Microsoft.Graph.Communications.Calls.Media.MediaSession..ctor(IGraphLogger logger, Guid mediaSessionId, IMediaSocketFactory socketFactory, AudioSocketSettings audioSocketSettings, IEnumerable`1 videoSocketSettings, VideoSocketSettings vbssSocketSettings, DataSocketSettings dataSocketSettings)
   at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientExtensions.CreateMediaSession(ICommunicationsClient client, AudioSocketSettings audioSocketSettings, IEnumerable`1 videoSocketSettings, VideoSocketSettings vbssSocketSettings, DataSocketSettings dataSocketSettings, Guid mediaSessionId)
   at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientExtensions.CreateMediaSession(ICommunicationsClient statefulClient, AudioSocketSettings audioSocketSettings, VideoSocketSettings videoSocketSettings, VideoSocketSettings vbssSocketSettings, DataSocketSettings dataSocketSettings, Guid mediaSessionId)
   at Sample.HueBot.Bot.Bot.CreateLocalMediaSession(Guid mediaSessionId) in C:\Users\Delphi-OleksiiG\Downloads\graph-samples\Samples\V1.0Samples\LocalMediaSamples\HueBot\HueBot\Bot\Bot.cs:line 266
   at Sample.HueBot.Bot.Bot.<JoinCallAsync>d__14.MoveNext() in C:\Users\Delphi-OleksiiG\Downloads\graph-samples\Samples\V1.0Samples\LocalMediaSamples\HueBot\HueBot\Bot\Bot.cs:line 136

Could you please assist, what am I missing here?

**Comment by oleksii-gudz** [comment]
I investigated one of my cluster nodes and detected that port 8445 is closed their (and on all other nodes as well). Looks like something went wrong and media port was not opened during startup, thus D:\SvcFab\_App\HueBotSFType_App5\HueBotPkg.Code.1.0.1\Startup.log doesn't have any errors...
Also, there are no errors in event viewer... 
How can I troubleshot that?

**Comment by oleksii-gudz** [comment]
If someone has encountered the same issue, check how many CPUs on your VM.  Media bot requires at least 2, otherwise it raised exception. Unfortunately it is not documented and not obvious.

**Comment by yurij-shinkaruk** [comment]
In Azure VM Standard D2_v2, there are 2 vCPUs that correlate to the core CPU at **1:1**.
In newer Standards (D2v3. D2v4 or D2v5) - the correlation between vCPU and core CPU is **2:1**, which means the Skype Bot Media SDK will not work with the above exception. 
So if you want to use VM types from the v3-5 Standards - make sure you have at least **4** vCPU.

**Comment by fahrudinip** [comment]
I get the same issue with "Standard F4s v2 (4 vcpus, 8 GiB memory)." Do you have any ideas on how to solve it?

**Comment by yurij-shinkaruk** [comment]
Try to ask MSFT there:
https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/146#issuecomment-572884677
