### ISSUE TITLE
Insufficient enterprise tenant permissions, cannot access this API.

### ISSUE THREAD

**Issue by CCNOAI** [microsoftgraph/microsoft-graph-comms-samples#276]
fail: VoiceRecorderAndPlaybackBot[1742746998]
      2020-07-06T23:05:11.5197Z 00000000-0000-0000-0000-000000000000 pid:23658 tid:47 (Bot.cs:247 NotificationProcessor_OnNotificationReceived):
      Caught an Exception running the task: Error processing notification /communications/calls/be1f0400-731f-489a-a110-5457d9a040c8 with scenario e5b6e28c-e545-4638-8f32-d8ff8a4e8fbf
      exception: Code: 7504
      Message: Insufficient enterprise tenant permissions, cannot access this API.
      Inner error:
      	AdditionalData:
      	date: 2020-07-06T23:05:11
      	request-id: 2df32658-90f2-4b97-a39e-5f18ed3d2063
      
      StackTrace:    at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.ValidateResponseAsync(HttpResponseMessage response)
         at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.SendHttpRequestAsync[T1,T2](IGraphRequest`1 graphRequest, CancellationToken cancellationToken)
         at Sample.Common.Transport.GraphClientExtensions.SendAsync[T](IGraphClient client, IBaseRequest request, RequestType requestType, String tenant, Guid scenarioId, CancellationToken cancellationToken) in /Users/benjaminharvey/Desktop/microsoft-graph-comms-samples-master/Samples/Common/Sample.Common/Transport/GraphClientExtensions.cs:line 107
         at Sample.VoiceRecorderAndPlaybackBot.Bot.Bot.BotRecordsIncomingCallAsync(String callId, String tenantId, Guid scenarioId) in /Users/benjaminharvey/Desktop/microsoft-graph-comms-samples-master/Samples/V1.0Samples/StatelessSamples/VoiceRecorderAndPlaybackBot/Bot/Bot.cs:line 456
         at Sample.VoiceRecorderAndPlaybackBot.Bot.Bot.NotificationProcessor_OnNotificationReceivedAsync(NotificationEventArgs args) in /Users/benjaminharvey/Desktop/microsoft-graph-comms-samples-master/Samples/V1.0Samples/StatelessSamples/VoiceRecorderAndPlaybackBot/Bot/Bot.cs:line 310
         at Sample.Common.CommonUtilities.ForgetAndLogExceptionAsync(Task task, IGraphLogger logger, String description, String memberName, String filePath, Int32 lineNumber) in /Users/benjaminharvey/Desktop/microsoft-graph-comms-samples-master/Samples/Common/Sample.Common/CommonUtilities.cs:line 40

**Comment by mosoftwareenterprises** [comment]
@CCNOAI did you resolve this?
I think its because your tenant has not authorised your bot.
