### ISSUE TITLE
RemoteMediaSample Failing During Execution

### ISSUE THREAD

**Issue by Todd442** [microsoftgraph/microsoft-graph-comms-samples#308]
I have the RemoteMediaSample deployed. 

**The sample calls the first attendee in list but then fails:**

The first attendee gets promoted to join, joins the meeting but the hears nothing. Of course the code has already failed by then.

The code failing is a blackbox:
**   var statefulCall = await this.Client.Calls().AddAsync(call, scenarioId: scenarioId).ConfigureAwait(false);
**

What are we missing?

Status Code: InternalServerError
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 9999
Message: Unkown internal Server Error.
Scenario Id: efec6d49-ba67-49a5-a9af-613167c64e54
Inner error:
	AdditionalData:
	date: 2020-08-14T15:10:09
	request-id: 5491fdbc-6e41-41b4-a074-aa4554978cb4
 ---> Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 9999
Message: Unkown internal Server Error.
Inner error:
	AdditionalData:
	date: 2020-08-14T15:10:09
	request-id: 5491fdbc-6e41-41b4-a074-aa4554978cb4

   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<SendAsync>d__11`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<GenerateEntityAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulCallCollection.<GenerateEntityAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<CreateStatefulResourceAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<GenerateStatefulResourceAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Sample.IncidentBot.Bot.Bot.<MakeCallAsync>d__29.MoveNext() in C:\Projects\Samples\V1.0Samples\RemoteMediaSamples\IncidentBot\Bot\Bot.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Sample.IncidentBot.Bot.Bot.<RaiseIncidentAsync>d__27.MoveNext() in C:\Projects\Samples\V1.0Samples\RemoteMediaSamples\IncidentBot\Bot\Bot.cs:line 222
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

**Comment by AyshwaryaRamakrishnan** [comment]
Yes, same issue I am observing too
