### ISSUE TITLE
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 8522

### ISSUE THREAD

**Issue by alexisconia** [microsoftgraph/microsoft-graph-comms-samples#330]
**Describe the issue**
My bot subscribes to unhandled exceptions and I receive regularly 

**Code Snippet**
Insert the code snippet if any.

**Expected behavior**
The call is stopped but I still receive this error

**Graph SDK (please complete the following information):**
Microsoft.Graph.Communications.Calls.Media 1.2.0.1702

**Call ID**
ec8cbd23-e6cf-4095-bf0c-d91192e40968

**Logs**
 A task has encountered an unobserved exception
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 8522
Message: Call not found.
Scenario Id: ec8cbd23-e6cf-4095-bf0c-d91192e40968
Inner error:
        AdditionalData:
        date: 2020-09-17T11:34:41
        request-id: 8f232da6-2d74-4133-ba3d-7cc4b52dbc7b
        client-request-id: ede4d02e-018b-4d3e-97a5-30c6fc0e2e95
 ---> Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 8522
Message: Call not found.
Inner error:
        AdditionalData:
        date: 2020-09-17T11:34:41
        request-id: 8f232da6-2d74-4133-ba3d-7cc4b52dbc7b
        client-request-id: ede4d02e-018b-4d3e-97a5-30c6fc0e2e95

   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Common.Transport.GraphHttpClient.<SendAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<SendAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulCall.<KeepAliveAsync>d__25.MoveNext()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Status Code: NotFound
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 8522
Message: Call not found.
Scenario Id: ec8cbd23-e6cf-4095-bf0c-d91192e40968
Inner error:
        AdditionalData:
        date: 2020-09-17T11:34:41
        request-id: 8f232da6-2d74-4133-ba3d-7cc4b52dbc7b
        client-request-id: ede4d02e-018b-4d3e-97a5-30c6fc0e2e95
 ---> Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: 8522
Message: Call not found.
Inner error:
        AdditionalData:
        date: 2020-09-17T11:34:41
        request-id: 8f232da6-2d74-4133-ba3d-7cc4b52dbc7b
        client-request-id: ede4d02e-018b-4d3e-97a5-30c6fc0e2e95

   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Common.Transport.GraphHttpClient.<SendAsync>d__24`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<SendAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulCall.<KeepAliveAsync>d__25.MoveNext()<---

**Comment by MaslinuPoimal** [comment]
Also getting this one on our backup bot, were you able to solve it?

**Comment by alexisconia** [comment]
Hi @MaslinuPoimal, No I was not able to solve it.
