### ISSUE TITLE
The Subscribe method may only be called when a RenderlessSink device is attached

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#362]
**Describe the issue**
Some times we get an exception like this:

`$>2020-11-10T11:57:09.4653242Z Error: BotMediaStream.cs:297 Unsubscribe
ScenarioId: d6491720-0d49-417c-b858-e2e237e0bea5
CallId: 891f0200-0c20-4e33-b876-e3b970228c7f
TenantId: fe380fea-xxxx
AppId: 8c8bd361-xxxx
AppName: Sample.PolicyRecordingBot.FrontEnd
Unsubscribing to video failed for the socket: 2 with exception
exception: Subscription failure.
The Subscribe method may only be called when a RenderlessSink device is attached.
StackTrace:    at Microsoft.Rtc.MPService.Stream.Subscribe(MPSubscriptionMode subscriptionMode, VideoSubscriptionSize videoSize, UInt32 sourceID, Boolean subscriptionCompletedEventRequested, MPStreamDirection direction)
   at Microsoft.Rtc.MPService.Context.Microsoft.Rtc.MPService.IInternalContext.Subscribe(MediaType mediaType, VideoSubscriptionSize videoSubscriptionSize, Int32 videoIndex, UInt32 msi)
   at Microsoft.Rtc.MPService.MPMediaSession.Subscribe(MediaType mediaType, VideoSubscriptionSize videoSubscriptionSize, Int32 videoIndex, UInt32 msi)
   at Microsoft.Skype.Bots.Media.Wrappers.MPMediaSessionWrapper.Subscribe(MediaType mediaType, VideoSize videoSize, UInt32 videoIndex, UInt32 msi)`

**Expected behavior**
We are not sure why this error occurs and whether it can be ignored.

**Call ID**
see above

**Logs**
see above

**Comment by ssulzer** [comment]
The error can be ignored. Do you see it occurring near call termination? (i.e., you are unsubscribing just as the bot's call is ending.)

But if you are not on the most recent Microsoft.Skype.Bots.Media nuget package, please update - https://www.nuget.org/packages/Microsoft.Skype.Bots.Media/1.19.0.25-alpha. Thanks.

**Comment by saraswat40** [comment]
Thanks. I am on the version you mentioned.
