### ISSUE TITLE
Media Platform failed to initialise ECS Timeout

### ISSUE THREAD

**Issue by midmohan** [microsoftgraph/microsoft-graph-comms-samples#37]
I get the following error when trying to start the hue bot locally(Using Azure Fabric Service and Ngrok)

"Media platform failed to initialize" 
Inner Exception :- InvalidOperationException: Failed to initialize platform configuration (ECS timeout).

Microsoft.Skype.ECS.Client Warning: 0 : 1_https://s2s.config.skype.com_https://use.config.skype.com : Request failed : request=[/config/v1/AzureService/1.0.0.0?DeploymentName=bebd7c91-9822-4990-abe3-a2d83df784cb&agents=SmartAgents]; retryCount=[1]; exception=[System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Skype.Seatbelt.Core.Helpers.DefaultClassifier.<ClassifyResult>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Skype.Seatbelt.Core.Blocks.HedgedResourcePool.LineWithFallback`2.<PostAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Skype.Seatbelt.Core.Blocks.HedgedResourcePool.ParallelRequestsExecutor`2.<PostAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Skype.Seatbelt.Core.Blocks.HedgedResourcePool.HedgedResourcePoolBlock`2.<PostCallAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Skype.Seatbelt.Core.Blocks.HedgedResourcePool.HedgedResourcePoolBlock`2.<PostAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Skype.Seatbelt.Core.Blocks.Retry.RetryBlock`2.<PostAsync>d__7.MoveNext()]
The thread 0x219c has exited with code 0 (0x0).
Microsoft.Skype.ECS.Client Error: 0 : Microsoft.Skype.ECS.Client.ECSClientConfigLoader : Exception of type 'Microsoft.Skype.Seatbelt.Core.Blocks.TimeLimit.TimeLimitException' was thrown.
The thread 0x10c has exited with code 0 (0x0).

**Comment by midmohan** [comment]
Able to get pass this

**Comment by 1fabi0** [comment]
I had the same Problem for me it was a problem with Newtonsoft.Json. So if somebody reads this having the same Issue, chekc your Newtonsoft.Json(is it in every Project same version, etc)
