### ISSUE TITLE
AudioVideoPlaybackBot.FrontEnd.Bot.Bot.JoinCallAsync fails with "Application reached the monthly call creation limit."

### ISSUE THREAD

**Issue by bughit** [microsoftgraph/microsoft-graph-comms-samples#385]
**Describe the issue**
joinCall requests to AudioVideoPlaybackBot are failing with the following response

```txt
Status Code: 429
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: UnknownError
Message: {"errorCode":"8529","message":"Application reached the monthly call creation limit.","instanceAnnotations":[]}
Scenario Id: 7383aa99-fd09-4ffc-83c7-fbc1cd7571f7
Inner error:
	AdditionalData:
	date: 2020-12-07T21:40:14
	request-id: b14b1f4d-926a-4abd-945e-a92c205a3f41
	client-request-id: 08aa3f09-3094-4e66-a4a7-efc4871c0d43
 ---> Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: UnknownError
Message: {"errorCode":"8529","message":"Application reached the monthly call creation limit.","instanceAnnotations":[]}
Inner error:
	AdditionalData:
	date: 2020-12-07T21:40:14
	request-id: b14b1f4d-926a-4abd-945e-a92c205a3f41
	client-request-id: 08aa3f09-3094-4e66-a4a7-efc4871c0d43

   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<ValidateResponseAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphAuthClient.<SendHttpRequestAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<SendAsync>d__11`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<GenerateEntityAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulCallCollection.<GenerateEntityAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<CreateStatefulResourceAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<GenerateStatefulResourceAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.AudioVideoPlaybackBot.FrontEnd.Bot.Bot.<JoinCallAsync>d__22.MoveNext() in C:\source\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\AudioVideoPlaybackBot\FrontEnd\Bot\Bot.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sample.AudioVideoPlaybackBot.FrontEnd.Http.JoinCallController.<JoinCallAsync>d__0.MoveNext() in C:\source\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\AudioVideoPlaybackBot\FrontEnd\Http\Controllers\JoinCallController.cs:line 46
```

from the log it looks POST https://graph.microsoft.com/v1.0/communications/calls is failing

```txt
$>2020-12-07T21:40:14.4336958Z Error: GraphAuthClient.cs:117 SendHttpRequestAsync
ScenarioId: 7383aa99-fd09-4ffc-83c7-fbc1cd7571f7
AppId: 
AppName: Sample.AudioVideoPlaybackBot.FrontEnd
TransactionDirection: Outgoing
TraceType: HttpResponse
ResponseTime: 8
request: POST https://graph.microsoft.com/v1.0/communications/calls
response: 429 429
headers:
  request-id: b14b1f4d-926a-4abd-945e-a92c205a3f41
  client-request-id: 08aa3f09-3094-4e66-a4a7-efc4871c0d43
  x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"East US","Slice":"SliceC","Ring":"5","ScaleUnit":"000","RoleInstance":"AGSFE_IN_52"}}
  scenario-id: 7383aa99-fd09-4ffc-83c7-fbc1cd7571f7
  Strict-Transport-Security: max-age=31536000
  Cache-Control: private
  Date: Mon, 07 Dec 2020 21:40:13 GMT
  Content-Length: 386
  Content-Type: application/json
{
  "error": {
    "code": "UnknownError",
    "message": "{\"errorCode\":\"8529\",\"message\":\"Application reached the monthly call creation limit.\",\"instanceAnnotations\":[]}",
    "innererror": {
      "date": "2020-12-07T21:40:14",
      "request-id": "b14b1f4d-926a-4abd-945e-a92c205a3f41",
      "client-request-id": "08aa3f09-3094-4e66-a4a7-efc4871c0d43"
    }
  }
}
```

**Comment by bughit** [comment]
According to https://docs.microsoft.com/en-us/graph/throttling there's a limit of 10,000 calls per month. But in this case the bot isn't initiating/creating calls, it's just getting a reference to an existing call (meeting), so should this even be subject to this limit?

**Comment by 1fabi0** [comment]
A call for a bot is a connection(each connection 1 audio socket up to 10 video sockets) to a Meeting, so if you join 100 times a meeting with the bot, 100 calls were taken from the Bots limit. I hope you understand this definition. If you have a application that is used by so many users that this 10 000 limit is reached you should maybe conntact Microsoft and ask for a contract with them 😄
