### ISSUE TITLE
 Failed to initialize platform configuration (ECS timeout).

### ISSUE THREAD

**Issue by saraswat40** [microsoftgraph/microsoft-graph-comms-samples#446]
**Describe the issue**
For the last few days we are running into the following exception while trying to start the PolicyComplianceBot.

We have looked at [this](https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/37) issue.

we have also updated our NewtonSoft packages as well as skype packages.

Microsoft.Skype.ECS.Client Error: 0 : Microsoft.Skype.ECS.Client.ECSClientConfigLoader : An error occurred while sending the request.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Error: 0 : Microsoft.Skype.ECS.Client.ECSClientConfigLoader : Unable to load configuration from any endpoint
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
Microsoft.Skype.ECS.Client Warning: 0 : Microsoft.Skype.ECS.Client.ECSOfflineFileCache : Unable to read from cache C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot. Cache does not exist.
The thread 0x277c has exited with code 0 (0x0).
The thread 0x3c has exited with code 0 (0x0).
Exception thrown: 'System.InvalidOperationException' in Microsoft.Skype.Bots.Media.dll
Exception thrown: 'Microsoft.Graph.Communications.Core.Exceptions.ServiceException' in Microsoft.Graph.Communications.Calls.Media.dll
'WaWorkerHost.exe' (CLR v4.0.30319: RdRuntime): Loaded 'C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\csx\Debug\roles\CRWorkerRole\approot\log4net.dll'. 
Exception thrown: 'Microsoft.Graph.Communications.Core.Exceptions.ServiceException' in Sample.PolicyRecordingBot.WorkerRole.dll
Microsoft.WindowsAzure.ServiceRuntime Critical: 31337 : Status Code: 0
Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Code: mediaInitializationFailure
Message: Media platform failed to initialize
 ---> System.InvalidOperationException: Failed to initialize platform configuration (ECS timeout).
   at Microsoft.Skype.Internal.Bots.Media.InternalMediaPlatform.Initialize(MediaPlatformSettings settings, IConfigurationManager configurationManager, Boolean isTest)
   at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientBuilderExtensions.SetMediaPlatformSettings(ICommunicationsClientBuilder statefulClientBuilder, MediaPlatformSettings mediaSettings)
   --- End of inner exception stack trace ---
   at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientBuilderExtensions.SetMediaPlatformSettings(ICommunicationsClientBuilder statefulClientBuilder, MediaPlatformSettings mediaSettings)
   at Sample.PolicyRecordingBot.FrontEnd.Bot.Bot.Initialize(Service service, IGraphLogger logger) in C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\FrontEnd\Bot\Bot.cs:line 98
   at Sample.PolicyRecordingBot.FrontEnd.Service.Start() in C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\FrontEnd\Service.cs:line 80
   at Sample.PolicyRecordingBot.WorkerRole.WorkerRole.OnStart() in C:\capture\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 106
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
Exception thrown: 'Microsoft.Graph.Communications.Core.Exceptions.ServiceException' in Microsoft.WindowsAzure.ServiceRuntime.dll
Microsoft.WindowsAzure.ServiceRuntime Critical: 1 : Unhandled Exception:

**Comment by olivermanumbas** [comment]
We are also experiencing the same error when running the AudioVideoPlaybackBot. The error appeared only this week and we have not changed anything in the codes.

**Comment by andir78** [comment]
Me too.  Found this when returning to our dev version to fix a bug and could not even start up the code.  Looks like there's an underlying problem for the Microsoft.Skype.Bots.Media nuget package?!

**Comment by AlexSapple** [comment]
Seem to be experiencing intermittent performance issues currently - haven't got enough telemetry my end to pick out exactly what's happening (so may not have any connection to this issue described above - working on confirming that) - but certainly having a bad time of it since 06-May (maybe earlier). In my case it's a media bot that's processing video data that seems to be getting video frames very late.

**Comment by marcinburak** [comment]
Same here. Working on PolicyComplianceBot project, since the last couple of days we can't start it due to "ECS timeout" exception even though we didn't make any changes to our code in the meantime.

**Comment by andir78** [comment]
Any updates?!  Anyone else having this issue?
This is still a problem for me.  Doesn't seem to be an issue for when the code is deployed into Azure (STAGE or PROD) but it definitely stops me from running locally which is crippling progress.

**Comment by olivermanumbas** [comment]
Managed to get past this by using TLS 1.2.
In our case we added the following code in WorkerRole.cs:

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;`

**Comment by andir78** [comment]
@olivermanumbas Adding the code you suggested did not work for me! Is there something extra needed?  I added the line _after_ the line
```ServicePointManager.DefaultConnectionLimit = 12```

**Comment by AlexSapple** [comment]
The following worked for me - I added this to `OnStart() ` of the WorkerRole. I am now connecting to calls quite happily (media platform initializes correctly)

```
if(RoleEnvironment.IsEmulated)
                ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

(you don't want to set the SecurityProtocol outside of emulation)

**Comment by andir78** [comment]
SORTED!!! 

Thanks, @olivermanumbas  and @AlexSapple.  My code is a modified version of the policy recording sample and in my scenario, I was setting the security protocol _after_ setting the media platform settings, which is obviously too late.  Quick reshuffle and we're up!!

**Comment by saraswat40** [comment]
Solution suggested by @olivermanumbas/@AlexSapple is working.
