### ISSUE TITLE
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt

### ISSUE THREAD

**Issue by anandshende06051994** [microsoftgraph/microsoft-graph-comms-samples#493]
Hi,

I am intermittently getting the following error whenever running the recording bot. 
`Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.Skype.Bots.Media.AudioFramePlayer.CopyMemory(IntPtr dest, IntPtr src, UInt32 count)
   at Microsoft.Skype.Bots.Media.AudioFramePlayer.<CopyAndSendData>d__46.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Skype.Bots.Media.AudioFramePlayer.CopyAndSendData(AudioMediaBuffer sourceBuffer, MediaBuffer destinationBuffer)
   at Microsoft.Skype.Bots.Media.AudioFramePlayer.<DequeueAndProcessAsync>d__47.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass4_0.<OutputAsyncCausalityEvents>b__0()
   at System.Runtime.CompilerServices.TaskAwaiter.<>c__DisplayClass11_0.<OutputWaitEtwEvents>b__0()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining, Task& currentTask)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()`

Can somebody help me with this ?

**Comment by 1fabi0** [comment]
It seems like you try to play audio into a call, but you are disposing sending buffers by yourself which causes that the memory where the audio was located that you try to play is already freed again that could also be the case for receiving, that you are trying to use a memory location of the audio buffer that is already freed again, the first step in receiving should be copying the audio buffers into managed code, which then uses garbage collection
