### ISSUE TITLE
[PolicyRecordingBot] No such address

### ISSUE THREAD

**Issue by XiaonuoGantan** [microsoftgraph/microsoft-graph-comms-samples#503]
Following the steps on https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot#create-an-application-instance, after provisioning a Cloud services (extended support) environment with an Azure bot, I'm blocked by the following error when a worker role instance tries to startup:

Starting role... Unhandled Exception:  No such host is known
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.GetInstancePublicIpAddress(String publicFqdn) in C:\Users\xgantan\execvision\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 381
   at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.Initialize() in C:\Users\xgantan\execvision\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 231
   at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration..ctor(IGraphLogger logger) in C:\Users\xgantan\execvision\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 118
   at Sample.PolicyRecordingBot.WorkerRole.WorkerRole.OnStart() in C:\Users\xgantan\execvision\microsoft-graph-comms-samples\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 92
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.

**Comment by alancejacob** [comment]
Similar error during the deployment

Recovering role... Unhandled Exception: No such host is known at System.Net.Dns.GetAddrInfo(String name) at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6) at System.Net.Dns.GetHostEntry(String hostNameOrAddress) at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.GetInstancePublicIpAddress(String publicFqdn) in C:\TeamsProjects\microsoft-graph\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 380 at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.Initialize() in C:\TeamsProjects\microsoft-graph\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 231 at Sample.PolicyRecordingBot.WorkerRole.WorkerRole.OnStart() in C:\TeamsProjects\microsoft-graph\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 92 at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum) at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0() at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx) at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) at System.Threading.ThreadHelper.ThreadStart() ' [2021-11-03T21:31:22Z] Last exit time: [2021/11/03, 21:31:24.378]. Last exit code: 0.

**Comment by lyuboSynergy** [comment]
I've experienced this problem. You should check **ServiceDnsName** and **ServiceCNAME** in ServiceConfiguration.Cloud.cscfg. What are their values? Can they be resolved? Is the certificate appropriate for ServiceCNAME?

**Comment by alancejacob** [comment]
> I've experienced this problem. You should check **ServiceDnsName** and **ServiceCNAME** in ServiceConfiguration.Cloud.cscfg. What are their values? Can they be resolved? Is the certificate appropriate for ServiceCNAME?

Thank You. Resolved the issue

**Comment by tekitalent** [comment]
Hello @alancejacob 
May I ask how did you resolve the issue please ?

Thanks
