### ISSUE TITLE
Operation AnswerAsync failed with using Microsoft.Graph version 4.22.0

### ISSUE THREAD

**Issue by kordina-AT** [microsoftgraph/microsoft-graph-comms-samples#528]
When I explicitly use Microsoft.Graph package 4.22.0 with Microsoft.Graph.Communications.Calls 1.2.0.4161, operation AnswerAsync failed with the error "Method not found", probably because parameters have been changed,  see [Answer](https://docs.microsoft.com/en-us/graph/api/call-answer?view=graph-rest-1.0&tabs=csharp).
The new parameter "participantCapacity" has been added.

Exception:
Method not found: 'Microsoft.Graph.ICallAnswerRequestBuilder Microsoft.Graph.ICallRequestBuilder.Answer(System.String, Microsoft.Graph.MediaConfig, System.Collections.Generic.IEnumerable`1<Microsoft.Graph.Modality>, System.Nullable`1<Int32>)'.

Stack trace:
   at Microsoft.Graph.Communications.Calls.StatefulCall.<AnswerAsync>d__28.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.Communications.Calls.StatefulCall.AnswerAsync(MediaConfig mediaConfig, IEnumerable`1 acceptedModalities, String callbackUri, Guid scenarioId, CancellationToken cancellationToken, Int32 participantCapacity)
   at Microsoft.Graph.Communications.Calls.CallExtensions.AnswerAsync(ICall call, IEnumerable`1 preFetchMedia, IEnumerable`1 acceptedModalities, String callbackUri, Guid scenarioId, CancellationToken cancellationToken)
   at Atlantis.Pro.Cti.Teams.App.Bot.CallHandler.<AnswerAsync>d__52.MoveNext() in C:\Users\kordina\source\repos\FrontStage\app\Pro\Cti.Teams\App\Bot\CallHandler.cs:line 171
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlantis.Pro.Cti.Teams.Session.CallOperation.<>c__DisplayClass10_0.<<RunAsync>b__0>d.MoveNext() in C:\Users\kordina\source\repos\FrontStage\app\Pro\Cti.Teams\App\Session\CallSession.cs:line 45
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Atlantis.Pro.Cti.Teams.Session.CallOperation.<RunAsync>d__10.MoveNext() in C:\Users\kordina\source\repos\FrontStage\app\Pro\Cti.Teams\App\Session\CallSession.cs:line 47

**Comment by 1fabi0** [comment]
work arround in #523 until the communication nuget packages are fixed

**Comment by kordina-AT** [comment]
Thank you @1fabi0 , I will be waiting for a new version
