### ISSUE TITLE
Error in AppHost.cs

### ISSUE THREAD

**Issue by gurujuu** [microsoftgraph/microsoft-graph-comms-samples#556]
The below line is throwing an exception

 _botService.Initialize(); 

Unhandled exception: Object reference not set to an instance of an object.
Exception Details:
press any key to exit...

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at RecordingBot.Console.Program.ExceptionHandler(Exception e) in C:\src\RecordingBot.Console\Program.cs:line 77
   at RecordingBot.Console.Program.Main(String[] args) in C:\src\RecordingBot.Console\Program.cs:line 57

Please help in analysing this issue

**Comment by 1fabi0** [comment]
The Initilialize section of the Bot Service tries to use the injected Settings but it seems like the Settings object itself is null or some settings on it are null

**Comment by 1fabi0** [comment]
I assume for your docker container you need to set environment variables in your container, you can see which environment variables from the `.env-template`-File, alternatively you could probably also set the values in the `.env-template`-File, then they are automatically loaded as environment variables when the application starts in the container

**Comment by RaiAmanRai** [comment]
Hi @1fabi0, I tried to publish the project to folder. It works well on the system where it was built but when i try to run it on a different system it throw me "Unhandled exception: Object reference not set to an instance of an object."

Any way I can get away with it, or deploy it in some way.
