### ISSUE TITLE
Policy Bot deployment Error in Azure cloud services(extended Support) from Visual studio

### ISSUE THREAD

**Issue by AjayDevulapalli** [microsoftgraph/microsoft-graph-comms-samples#561]
Deployment of Policy Bot sample is failing at Worker role throwing error: No such host is known

Unhandled Exception:  No such host is known
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.GetInstancePublicIpAddress(String publicFqdn) in ./Botcodeupdated\microsoft-graph\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 381
   at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.Initialize() in ./Botcodeupdated\microsoft-graph\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 230
   at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration..ctor(IGraphLogger logger) in ./\Botcodeupdated\microsoft-graph\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 118
   at Sample.PolicyRecordingBot.WorkerRole.WorkerRole.OnStart() in ./\Botcodeupdated\microsoft-graph\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 95
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.

**Below is the Cloud.config file settings.** 

*<?xml version="1.0" encoding="utf-8"?>
<ServiceConfiguration serviceName="PolicyRecordingBot" xmlns="http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceConfiguration" osFamily="7" osVersion="*" schemaVersion="2015-04.2.6">
  <Role name="CRWorkerRole">
    <Instances count="2" />
    <ConfigurationSettings>
      
     <Setting name="ServiceDnsName" value="xxxxx.westeurope.cloudapp.azure.com" /> 
      
     <Setting name="ServiceCNAME" value="xxxxx.domain.com" /> 
       
      <Setting name="DefaultCertificate" value=" Wildcard certificate created and thumbprint value used" /> 
      <Setting name="APPINSIGHTS_INSTRUMENTATIONKEY" value="" /> 
    </ConfigurationSettings> 
    <Certificates> 
      <Certificate name="Default" thumbprint="xxxxx-xxxx-xxxx-xxxxx" thumbprintAlgorithm="sha1" /> 
    </Certificates> 
  </Role>
  <NetworkConfiguration>
    <VirtualNetworkSite name="Virtual networkname " />
    <AddressAssignments>
      <InstanceAddress roleName="CRWorkerRole">
        <Subnets>
          <Subnet name="default" />
        </Subnets>
      </InstanceAddress>
    </AddressAssignments>
    
  </NetworkConfiguration>
</ServiceConfiguration>

A Wild card certificate is created and pointed tp the DNS name with a custom CName value xyz.domin.com and pointed to the default Azure cloud DNS name xyz..westeurope.cloudapp.azure.com

**Comment by omarEmocional** [comment]
Hi! 
- Is publishing to Azure Cloud Service (classic) supported ? 
- How do we convert from Azure Cloud Service (extended Support) to Azure Cloud Service (classic)  , is there an easy way for this ?

**Comment by tsubasaxZZZ** [comment]
@1fabi0 
Could you tell me if you have any plans to support Cloud Service(extended support) or VMMSS?

**Comment by 1fabi0** [comment]
I think it is possible vmss and cloud service... I'm not a Microsoft employee neither I am a user of the two services... I use AKS which then internally uses vmss for the nodes... But all you need to be able to, is to route a tcp connection to the instance that is running a bot and http requests.

**Comment by ajayraaviv** [comment]
I received the same error. The suggestion from this issue helped me #477
