### ISSUE TITLE
Audio Healing is not supported

### ISSUE THREAD

**Issue by facundoctes** [microsoftgraph/microsoft-graph-comms-samples#595]
**Describe the issue**
Trying to invite the bot into a Microsoft Teams meeting with EnableAudioHealingForUnmixed in true throws an exception "Audio Healing is not supported",  with EnableAudioHealingForUnmixed set to false it works fine

I googled when it's not supported but found nothing.

**Code Snippet**
`new AudioSocketSettings
                {
                    StreamDirections = StreamDirection.Sendrecv,
                    SupportedAudioFormat = AudioFormat.Pcm16K,
                    ReceiveUnmixedMeetingAudio = true,
                    EnableAudioHealingForUnmixed = true,
                },`

Microsoft.Skype.Bots.Media, Version=1.23.0.49

`System.InvalidOperationException: Audio Healing is not supported
   at Microsoft.Skype.Internal.Bots.Media.InternalMediaPlatform.CreateMediaConfiguration(IAudioSocket audioSocket, IList`1 videoSockets, IVideoSocket vbssSocket, IDataSocket dataSocket)
   at Microsoft.Graph.Communications.Calls.Media.MediaSocketFactory.CreateMediaConfiguration(IAudioSocket audioSocket, IEnumerable`1 videoSockets, IVideoSocket vbssSocket, IDataSocket dataSocket)
   at Microsoft.Graph.Communications.Calls.Media.MediaSession.GetMediaConfiguration()
   at Microsoft.Graph.Communications.Calls.StatefulCallCollection.AddAsync(Call resource, IMediaSession mediaSession, Guid scenarioId, CancellationToken cancellationToken)
   at Microsoft.Graph.Communications.Calls.CallCollectionExtensions.AddAsync(ICallCollection callCollection, JoinMeetingParameters parameters, Guid scenarioId, CancellationToken cancellationToken)`

**Comment by ssulzer** [comment]
Hi @facundoctes 
The EnableAudioHealingForUnmixed feature is currently in private preview. I expect it will become publicly available later this year in a newer Microsoft.Skype.Bots.Media SDK update.

Can you please share your scenario (e.g., compliance recording) or your bot's use of unmixed audio (e.g., speech recognition/transcription)?

The purpose of this feature: for a bot receiving unmixed audio from the Teams meeting, by default, there is no "healing" or "concealment" of glitches or random packet loss on the call leg between the Teams meeting server and the bot; this feature will add such healing. If the bot is performing speech analysis/recognition on the unmixed audio content, enabling this healing feature is not expected to make any difference (e.g., on word recognition accuracy).
(Also, packet loss between the Teams meeting server and the bot is also quite rare/minimal given both are running in Azure.)

Thanks.

**Comment by ssulzer** [comment]
@dcherubini 
Good question, thanks! The EnableAudioHealingForUnmixed and EnableLocalAudioMixingForUnmixed features are in "public preview," available to any developer who wishes to try them out. Right now, I recommend caution about using these new features in any production scenario.

**Comment by dcherubini** [comment]
@ssulzer Thanks for the information. I have one more question: is version [1.26.0.94](https://www.nuget.org/packages/Microsoft.Skype.Bots.Media/1.26.0.94-alpha) required to use the `EnableAudioHealingForUnmixed` flag or can it be enabled in previous versions of the SDK too?

**Comment by ssulzer** [comment]
@dcherubini 
You'll need to use version 1.26.0.94 to access that feature.
