### ISSUE TITLE
Unhandled Exception:  No such host is known

### ISSUE THREAD

**Issue by tekitalent** [microsoftgraph/microsoft-graph-comms-samples#606]
**Describe the issue**
We are following the exact steps, however, when we start the CRWorkerRole_IN_0 in the web service, we get the attached error or below pasted.
Thanks for any help !

Unhandled Exception:  No such host is known
   at System.Net.Dns.GetAddrInfo(String name)
   at System.Net.Dns.InternalGetHostByName(String hostName, Boolean includeIPv6)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at Sample.ComplianceRecordingBot.WorkerRole.AzureConfiguration.GetInstancePublicIpAddress(String publicFqdn) in D:\microsoft-graph-comms-samples-TeamsBot\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\WorkerRole\AzureConfiguration.cs:line 380
   at Sample.ComplianceRecordingBot.WorkerRole.AzureConfiguration.Initialize() in D:\microsoft-graph-comms-samples-TeamsBot\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\WorkerRole\AzureConfiguration.cs:line 231
   at Sample.ComplianceRecordingBot.WorkerRole.WorkerRole.OnStart() in D:\microsoft-graph-comms-samples-TeamsBot\Samples\BetaSamples\LocalMediaSamples\ComplianceRecordingBot\WorkerRole\WorkerRole.cs:line 92
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

' [2022-12-01T13:02:15.000Z] Last exit time: [2022/12/01, 13:02:17.510]. Last exit code: 0.
[error code.txt](https://github.com/microsoftgraph/microsoft-graph-comms-samples/files/10132633/error.code.txt)

**Code Snippet**
Insert the code snippet if any.

**Expected behavior**

**Graph SDK (please complete the following information):**

**Call ID**
Provide the list call ids that encountered this issue. Include the time in UTC/GMT when these call have occurred.

**Logs**
If required, please add [logs](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Logging.html) from the SDK. (Please remove any PII from the logs before uploading)

**Additional context**

**Comment by hwilliamsdtx** [comment]
I think this is the same issue as https://github.com/microsoftgraph/microsoft-graph-comms-samples/issues/477
