### ISSUE TITLE
Following the steps on ComplianceRecordingSample I am getting exception

### ISSUE THREAD

**Issue by diegoriera** [microsoftgraph/microsoft-graph-comms-samples#740]
https://github.com/microsoftgraph/microsoft-graph-comms-samples/tree/master/Samples/V1.0Samples/LocalMediaSamples/PolicyRecordingBot

I followed all steps on this deployment, however the exception is occurring during startup:
Unhandled Exception:  Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Sample.PolicyRecordingBot.WorkerRole.AzureConfiguration.Initialize() in C:\CommsSDK\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\AzureConfiguration.cs:line 212
   at Sample.PolicyRecordingBot.WorkerRole.WorkerRole.OnStart() in C:\CommsSDK\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 95
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by diegoriera** [comment]
@BalajiUmmadisetti please check
