### ISSUE TITLE
Media platform failed to initialize

### ISSUE THREAD

**Issue by DynTechieBibin** [microsoftgraph/microsoft-graph-comms-samples#784]
Exception:
Unable to load DLL 'NativeMedia' or one of its dependencies.

This exception occurs on the line: 
                builder.SetMediaPlatformSettings(mediaPlatformSettings);

var mediaPlatformSettings = new MediaPlatformSettings()
{
    MediaPlatformInstanceSettings = new MediaPlatformInstanceSettings()
    {
        CertificateThumbprint = sthumbprint,
        InstanceInternalPort = internalPort,
        InstancePublicIPAddress = IPAddress.Any,
        InstancePublicPort = publicPort,
        ServiceFqdn = config.ServiceFqdn
    },
    ApplicationId = config.APP_ID,
};

![mediabot](https://github.com/user-attachments/assets/d3deff24-3e30-4bb0-91ca-a8ee9f3929a4)

**Comment by leroypijlman** [comment]
Make sure you have WMF enabled/installed and vcredist installed (windows only)

**Comment by DynTechieBibin** [comment]
Install package Microsoft.Skype.Bots.Media. Even though it is within Microsoft.Graph.Communications.Calls.Media package, it seems the whole skype bot dependent dlls are not there.

**Comment by InDieTasten** [comment]
Congrats to finding your own solution!

I guess you could also close the issue then :)

**Comment by tranguyendinh** [comment]
Hi guys, i try to run echobot locally, but have this issue, do u have any idea for this 

Echo Bot Service is starting...
fail: EchoBot.EchoBotWorker[0]
      Media platform failed to initialize
      Status Code: 0
      Microsoft.Graph.Communications.Core.Exceptions.ServiceException: Media platform failed to initialize
       ---> System.ArgumentException: CertificateThumbprint (Parameter 'Could not find a matching certificate for thumbprint 9E95EBE782871401573B547F603FCD2D797FFDD6')
         at Microsoft.Skype.Internal.Bots.Media.InternalMediaPlatform.Initialize(MediaPlatformSettings settings, IConfigurationManager configurationManager, Boolean isTest)
         at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientBuilderExtensions.SetMediaPlatformSettings(ICommunicationsClientBuilder statefulClientBuilder, MediaPlatformSettings mediaSettings)
         --- End of inner exception stack trace ---
         at Microsoft.Graph.Communications.Calls.Media.MediaCommunicationsClientBuilderExtensions.SetMediaPlatformSettings(ICommunicationsClientBuilder statefulClientBuilder, MediaPlatformSettings mediaSettings)
         at EchoBot.Bot.BotService.Initialize() in C:\microsoft-graph-comms-samples\Samples\PublicSamples\EchoBot\src\EchoBot\Bot\BotService.cs:line 141
         at EchoBot.BotHost.StartAsync() in C:\microsoft-graph-comms-samples\Samples\PublicSamples\EchoBot\src\EchoBot\BotHost.cs:line 138
         at EchoBot.EchoBotWorker.ExecuteAsync(CancellationToken stoppingToken) in C:\microsoft-graph-comms-samples\Samples\PublicSamples\EchoBot\src\EchoBot\EchoBotWorker.cs:line 24

**Comment by InDieTasten** [comment]
@tranguyendinh Your issue is unrelated. The error message you shared is pretty clear about the cause of the issue:
> ---> System.ArgumentException: CertificateThumbprint (Parameter 'Could not find a matching certificate for thumbprint 9E95EBE782871401573B547F603FCD2D797FFDD6')

If you need more help, I'd suggest opening a separate issue to keep things searchable
