### ISSUE TITLE
Failed to load role entrypoint.

### ISSUE THREAD

**Issue by garaya-cmw** [microsoftgraph/microsoft-graph-comms-samples#792]
**Describe the issue**
I am implementing the recording bot that is published on the site, I have followed the indicated documentation step by step, but when I try to publish it shows the following Issue

**Graph SDK:**
 -  Version: 8.0.404

**Logs**
Failed to load role entrypoint.  System.IO.FileLoadException: Could not load file or assembly 'System.Text.Encodings.Web, Version=6.0.0.0, Culture=neutral, PublicKeyToken=XXXXXXXXXXXX' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
       at Microsoft.Graph.Communications.Common.OData.ODataConfiguration.FillODataJsonSerializerSettings(Boolean addOdataType, JsonSerializerOptions settings)
       at Microsoft.Graph.Communications.Common.OData.ODataConfiguration..ctor(Boolean addOdataType, Assembly[] odataAssemblies)
       at Microsoft.Graph.Communications.Common.Telemetry.Obfuscation.ObfuscationConfiguration.SetObfuscationEngine(IObfuscationEngine engine, Boolean addOdataType, ObfuscationMember[] members)
       at Microsoft.Graph.Communications.Common.Telemetry.Obfuscation.ObfuscationConfiguration..ctor(IObfuscationEngine engine, IEnumerable`1 filters, Boolean addOdataType, ObfuscationMember[] members, Assembly[] assemblies)
       at Microsoft.Graph.Communications.Common.Telemetry.Obfuscation.HashingObfuscationConfiguration..ctor(IEnumerable`1 filters, Boolean addOdataType, ObfuscationMember[] members)
       at Microsoft.Graph.Communications.Common.Telemetry.GraphLogger..ctor(String component, IEnumerable`1 properties, Boolean redirectToTrace, ObfuscationConfiguration obfuscationConfiguration)
       at Sample.PolicyRecordingBot.WorkerRole.WorkerRole..ctor() in C:\botKC\botKC\Samples\V1.0Samples\LocalMediaSamples\PolicyRecordingBot\WorkerRole\WorkerRole.cs:line 46
       --- End of inner exception stack trace ---
       at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
       at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
       at System.Activator.CreateInstance(Type type, Boolean nonPublic)
       at System.Activator.CreateInstance(Type type)
       at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.GetRoleEntryPoint(Assembly entryPointAssembly)
       at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.CreateRoleEntryPoint(RoleType roleTypeEnum)
       at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)' [2024-11-26T21:06:43.000Z] Last exit time: [2024/11/26, 21:06:44.058]. Last exit code: 0.

**Comment by tomzeni** [comment]
Hello, we're experiencing the same issue. Could you kindly share how you resolved it?
