### ISSUE TITLE
PsiBot Error Code 9999 - Unknown internal server error

### ISSUE THREAD

**Issue by yonatand-rain** [microsoftgraph/microsoft-graph-comms-samples#794]
**Describe the issue**
I cloned the PsiBot example and followed all the steps,
When the program gets to `var call = await _botService.JoinCallAsync(joinCallBody).ConfigureAwait(false);` it throws an Unknown internal server error.
```
Code: 9999
Message: Unknown internal server error.
Scenario Id: 6e72d6d1-9a3d-4444-b0bc-134c45ca9604
Inner error:
	
```

**Expected behavior**
The example should run.

**Graph SDK (please complete the following information):**
 - Version 9.0.101
 ( Got it from C:\Program Files\dotnet\sdk - I don't know if this is what's needed )

**Call ID**
Don't have call ids

**Logs**
If required, please add [logs](https://microsoftgraph.github.io/microsoft-graph-comms-samples/docs/articles/Logging.html) from the SDK. (Please remove any PII from the logs before uploading)

**Additional context**
Stack Trace:
```
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<ValidateAndWrapAsync>d__12`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Client.Transport.GraphClientWrapper.<SendAsync>d__11`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<GenerateEntityAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Calls.StatefulCallCollection.<GenerateEntityAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<CreateStatefulResourceAsync>d__31.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.Communications.Resources.StatefulResourceCollection`4.<GenerateStatefulResourceAsync>d__22.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PsiBot.Services.Bot.BotService.<JoinCallAsync>d__13.MoveNext() in C:\Users\ASUS F15\Projects\microsoft-bot-test\PsiBot\PsiBot.Service\Bot\BotService.cs:line 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PsiBot.Services.Controllers.JoinCallController.<JoinCallAsync>d__4.MoveNext() in C:\Users\ASUS F15\Projects\microsoft-bot-test\PsiBot\PsiBot.Service\Controllers\JoinCallController.cs:line 68
```

**Comment by wo-yashsinghvi** [comment]
@yonatand-rain I am too facing this issue. How did you resolve it?

**Comment by wo-yashsinghvi** [comment]
@yonatand-rain I hope you're doing well. I am currently facing syntax errors in the BotService.cs and CallHandler.cs files after updating the package as per the instructions. Would it be possible for you to share the updated files, or perhaps we can connect for a few minutes to troubleshoot?

I understand that time is valuable, but I’m in urgent need of getting the streams working for my project. You can reach me at yash.webosmotic@gmail.com, or feel free to share your contact details, and I will get in touch.

Looking forward to your help.

**Comment by wo-yashsinghvi** [comment]
@yonatand-rain I'm still struggling with this. If you have any deprecated code that you've already fixed, that would be really helpful. I'd really appreciate any assistance you can provide.

**Comment by Krishnanunni333** [comment]
@wo-yashsinghvi you can try out my forked repo if needed https://github.com/Krishnanunni333/microsoft-graph-comms-samples
branch: krishnanunnib/working-psi-bot.

**Comment by wo-yashsinghvi** [comment]
@Krishnanunni333 Thanks for sharing the repo, man. I had already completed the required parts for my project, so what I ended up doing was using the EchoBot—since it was working perfectly—and then added video support by integrating code from the PSI Bot. But I really appreciate your input! It would be helpful for people who are struggling to run PSI Bot.
